package com.example.domain.models.actionLog

enum class ActionType {
    AUTHORIZATION,
    CREATE_BANK_ACCOUNT,
    CHANGE_STATUS_BANK_ACCOUNT_BY_CLIENT,
    CHANGE_STATUS_BANK_ACCOUNT_BY_COMPANY,
    CHANGE_STATUS_BANK_ACCOUNT_BY_MANAGER,
    REQUEST_TO_SALARY_PROJECT_BY_CLIENT,
    RECALL_TO_SALARY_PROJECT_BY_CLIENT,
    REQUEST_TO_SALARY_PROJECT_BY_COMPANY,
    CHANGE_STATUS_SALARY_PROJECT,
    ACCEPT_CREDIT,
    TRANSFER,
    CANCEL_TRANSFER
}